from typing import Any, Optional


class DefinePrinterName:
	def __init__(self, printerName, printerDescription) -> None:
		"""
		The printer’s network name and description can be set using the ^KN command. ^KN is designed to make your Zebra printer easy for users to identify. The name the administrator designates is listed on the configuration label and on the Web page generated by the printer.
		"""
		self.__printerName = printerName
		self.__printerDescription = printerDescription

	def __str__(self) -> str:
		format = f"^KN{self.__printerName},{self.__printerDescription}"
		return format
